// Names and paths shared across the installer. Kept in one place so the CLI,
// commands, and tests agree on where things live.

export const PACK_NAME = 'qa-engineer';

// Files the installer writes into the target project root.
export const CONFIG_FILE = 'qa.config.json';
export const LOCKFILE = 'qa-lock.json';

// The pack's private working directory inside a target project.
export const QA_DIR = '.qa';
export const BACKUP_DIR = `${QA_DIR}/backups`;

// Marker line prepended to every generated invocation wrapper. Wrappers are
// disposable build artifacts; this line tells humans and `verify` that the file
// is pack-owned and regenerated, never hand-edited.
export const GENERATED_MARKER =
  'Generated by qa-engineer — do not edit. Regenerate with: qa install --force';

// Process exit codes. Stable so scripts and CI can branch on them.
export const EXIT = {
  OK: 0,
  FAILURE: 1, // an operation failed
  USAGE: 2, // the command line was wrong
  CONFLICT: 3, // refused to overwrite un-owned files without --force
  VERIFY: 4, // installed files drifted from the lockfile
  ENVIRONMENT: 5, // the environment cannot support the requested operation
};

// The two canonical skill discovery directories. Every target agent reads one
// of these; agent-specific directories are alternatives, not additions, so the
// planner installs each skill once per unique directory (no duplicates).
export const SHARED_SKILLS_DIR = '.agents/skills';
export const CLAUDE_SKILLS_DIR = '.claude/skills';
